<%
require 'yaml'
formula = YAML.load_file('metadata.yml')
formula_name = formula['name']
%>
---

driver:
  name: vagrant
  hostname: freebsd.ci.local
  linked_clone: true
  cache_directory: false

provisioner:
  name: salt_solo
  bootstrap_url: https://raw.githubusercontent.com/Perceptyx/kitchen-salt/freebsd_assets_fix/assets/install.sh
  salt_install: bootstrap
  <% if ENV['SALT_BOOTSTRAP_URL'] %>
  salt_bootstrap_url: <%= ENV['SALT_BOOTSTRAP_URL'] %>
  <% end %>
  salt_copy_filter:
    - .kitchen
    - .git
    - .ssh
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'debug' %>
  salt_version: latest
  pillars-from-files:
    <%= formula_name %>.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - <%= formula_name %>
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'debug' %>
  formula: <%= formula_name %>
  state_top:
    base:
      '*':
        - <%= formula_name %>

platforms:
  - name: freebsd-10.4
  - name: freebsd-11.1
  - name: freebsd-11.2

suites:
  - name: default
