<%
require 'yaml'
formula = YAML.load_file('metadata.yml')
formula_name = formula['name']
%>
---

driver:
  name: vagrant
  hostname: freebsd.ci.local

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: <% ENV['SALT_BOOTSTRAP_URL'] || 'https://bootstrap.saltstack.com' %>
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'debug' %>
  salt_version: 2017.7.3
  pillars-from-files:
    <%= formula_name %>.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - <%= formula_name %>
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'debug' %>
  formula: <%= formula_name %>
  state_top:
    base:
      '*':
        - <%= formula_name %>

platforms:
  - name: freebsd-10.3
    driver:
      cache_directory: false
  - name: freebsd-11.1
    driver:
      cache_directory: false

suites:
  - name: default
